spring:
  application:
    name: RABBIT-PRODUCER
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  config:
    import: configserver:${CONFIG_SERVER_ADDRESS:http://localhost:8085} 

server:
  port: 9081
